Numpy is a multi-dimensional array (1D arrays , 2D arrays , ....)

List are very slow NumPy are very fast
 - NumPy uses fixed type
 - In numpy no type checking when iterating through objects
 - numpy uses contiguous memory
 

In [7]:
#Load in NumPy
import numpy as np

Basics

In [6]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [7]:
b = np.array([[1,3,5,7,9],[0,2,4,6,8]])
print(b)

[[1 3 5 7 9]
 [0 2 4 6 8]]


In [8]:
#to get dimension
b.ndim

2

In [9]:
#to get shape
b.shape

(2, 5)

In [ ]:
#to get the type
a.dtype # default type

dtype('int64')

In [14]:
#if we want to specifies the type to take up less size
c = np.array([1,3,5,7,9], dtype='int16')
c.dtype

dtype('int16')

In [15]:
#get size
c.itemsize

2

In [ ]:
b.itemsize #in bytes

8

In [ ]:
#get total size
b.size * b.itemsize #or we can use b.nbytes

80

In [19]:
b.nbytes

80

In [21]:
d =np.array([2.0,3.0,4.4]) #float
d.itemsize

8

In [22]:
a.itemsize

8

Accessing/Changing specific elements, rows, columns, etc

In [41]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)
a.shape

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


(2, 7)

In [42]:
#get specific element [row,column]
a[1,5] #or a[1,-2]

np.int64(13)

In [43]:
#to get a specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [44]:
#to get a specific column
a[:,3]

array([ 4, 11])

In [45]:
#get a 2,4,6 element from the first row
a[0,1::2]

array([2, 4, 6])

In [46]:
#changing a value
a[1,5] = 15
print(a)
a[:,3]=[8,16]
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 15 14]]
[[ 1  2  3  8  5  6  7]
 [ 8  9 10 16 12 15 14]]


3D

In [ ]:
b = np.array([
    [[1,2],[3,4],[5,6],[7,8]]
    ])
print(b)

[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


In [48]:
b.shape

(1, 4, 2)

In [ ]:
#to get a specific elememt
#print a 4 number in 3d array
b[0,1,1]

np.int64(4)

In [53]:
#replace
b[:,1,:]

array([[3, 4]])

In [56]:
b[:,1,:]=[[9,9]]
print(b)

[[[1 2]
  [9 9]
  [5 6]
  [7 8]]]


Initializing Different Types of Arrays

In [61]:
#all 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [62]:
np.zeros((3,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [64]:
#all 1's matrix
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [66]:
z=np.ones((2,4), dtype="int32")
z.dtype


dtype('int32')

In [68]:
# Any other number
np.full((2,3),99,dtype='float32')

array([[99., 99., 99.],
       [99., 99., 99.]], dtype=float32)

In [69]:
#Any other number (full_like)
np.full_like(z, 4)

array([[4, 4, 4, 4],
       [4, 4, 4, 4]], dtype=int32)

In [70]:
#random decimal number
np.random.rand(3,2)

array([[0.18552692, 0.57528919],
       [0.50219212, 0.80604734],
       [0.83002069, 0.57380027]])

In [ ]:
#random decimal number
np.random.random_sample(z.shape)

array([[0.3207875 , 0.53783008, 0.37573692, 0.9510223 ],
       [0.4536664 , 0.56142518, 0.06764859, 0.30963075]])

In [ ]:
 #random integer values
np.random.randint(5, size=(3,2)) # here the 5 means it generate random element fron 0 to 4

array([[0, 2],
       [0, 4],
       [1, 2]], dtype=int32)

In [85]:
np.random.randint(-5,5, size=(3,4))

array([[-3,  0, -4, -3],
       [-3, -5,  1,  0],
       [ 0, -3, -2,  3]], dtype=int32)

In [ ]:
#identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [93]:
#repeat an array
arr=np.array([[1,2,3,4]]) #2d array
r=np.repeat(arr,3,axis=0)
print(r)

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]


In [96]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z #or output[1:4,1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Be careful when copying arrays

In [98]:
a=np.array([1,2,3,4])
b=a # a variable b point to the same thing as a does it is not a copy
b[0]=100
print(b)
print(a)  #even a is also change

[100   2   3   4]
[100   2   3   4]


In [99]:
a=np.array([1,2,3,4])
b=a.copy()
b[0]=100
print(b)
print(a)

[100   2   3   4]
[1 2 3 4]


Mathematics

In [103]:
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [104]:
a+2

array([3, 4, 5, 6, 7])

In [105]:
a-2

array([-1,  0,  1,  2,  3])

In [106]:
a*2

array([ 2,  4,  6,  8, 10])

In [108]:
a/2

array([1. , 1.5, 2. , 2.5, 3. ])

In [109]:
a+=2
a

array([4, 5, 6, 7, 8])

In [112]:
b=np.array([1,0,0,1])
c=np.array([0,1,1,0])
b+c

array([1, 1, 1, 1])

In [115]:
print(a)
a**2

[4 5 6 7 8]


array([16, 25, 36, 49, 64])

In [116]:
#take the sin
np.sin(a)

array([-0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825])

In [117]:
np.cos(a)

array([-0.65364362,  0.28366219,  0.96017029,  0.75390225, -0.14550003])

Linear Algebra

In [118]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [121]:
c=a@b #@ operator
print(c)

[[6. 6.]
 [6. 6.]]


In [122]:
C = a.dot(b)
print(C)

[[6. 6.]
 [6. 6.]]


In [123]:
#find the determinant
x=np.identity(3)
np.linalg.det(x)


np.float64(1.0)

Statistics

In [125]:
s = np.array([[1,2,3],[4,5,6]])
print(s)

[[1 2 3]
 [4 5 6]]


In [126]:
np.min(s)

np.int64(1)

In [127]:
np.max(s)

np.int64(6)

In [ ]:
np.min(s,axis=1) # Minimum value in first row and second row

array([1, 4])

In [131]:
np.sum(s)

np.int64(21)

Reorganizing arrays

In [134]:
b = np.array([[1,2,3,4],[5,6,7,8]])
print(b)
b.shape

[[1 2 3 4]
 [5 6 7 8]]


(2, 4)

In [137]:
print(b.reshape((4,2)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [138]:
#vertically stacking vectors
a1 = np.array([1,2,3])
a2=np.array([4,5,6])
np.vstack([a1,a2])

array([[1, 2, 3],
       [4, 5, 6]])

In [140]:
np.vstack([a1,a2,a1])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3]])

In [141]:
# Horizontal stack
h1=np.ones((2,4))
h2=np.zeros((2,2))
np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

In [148]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
print(np.vstack((v1,v2)))
print(np.hstack((v1,v2)))

[[1 2 3 4]
 [5 6 7 8]]
[1 2 3 4 5 6 7 8]


Miscellaneous

In [22]:
#Load Data from File
data=np.genfromtxt('data.txt',delimiter=',')
data.astype('int32')
print(data)

[[ 1. 23. 64. 45.]
 [10. 11. 53. 79.]
 [53. 89. 35. 99.]]


In [13]:
#Boolean Masking and Advanced Indexing
data>40

array([[False, False,  True,  True],
       [False, False,  True,  True],
       [ True,  True, False,  True]])

In [14]:
data[data>40]

array([64., 45., 53., 79., 53., 89., 99.])

In [17]:
a=np.array([1,2,3,4,5,6,7,8])
a[[1,3,6]]

array([2, 4, 7])

In [23]:
np.any(data > 50, axis=0)

array([ True,  True,  True,  True])

In [26]:
np.all(data>40,axis=0)

array([False, False, False,  True])

In [28]:
(~((data>50) & (data<100)))

array([[ True,  True, False,  True],
       [ True,  True, False, False],
       [False, False,  True, False]])

In [29]:
((data>50) & (data<100))

array([[False, False,  True, False],
       [False, False,  True,  True],
       [ True,  True, False,  True]])