NumPy

In [1]:
import numpy as np

In [3]:
a = np.array([1,2,3,4,5])

In [4]:
a.shape

(5,)

In [6]:
a.ndim

1

In [7]:
a.dtype

dtype('int64')

In [9]:
a.itemsize

8

In [10]:
a.size

5

In [11]:
b = np.array([[1,2,3,4],[5,6,7,8]])
b.shape

(2, 4)

In [40]:
c = np.array([[44,55,66,77],[88,99,100,110]])
print(c)
c.shape

[[ 44  55  66  77]
 [ 88  99 100 110]]


(2, 4)

In [41]:
b[0:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [42]:
c[:]

array([[ 44,  55,  66,  77],
       [ 88,  99, 100, 110]])

In [43]:
c[:,0]

array([44, 88])

In [44]:
c[:,2:]

array([[ 66,  77],
       [100, 110]])

In [51]:
d= np.array([[[12,24,36,48],
              [77,70,80,90],
              [45,68,72,32],
              [74,12,36,52]]])

In [63]:
d[:,:1,2:]

array([[[36, 48]]])

In [59]:
d[:,2:,2:]

array([[[72, 32],
        [36, 52]]])

In [65]:
d[:,1:3,1:3]

array([[[70, 80],
        [68, 72]]])

Reshape of an array

In [68]:
c.shape

(2, 4)

In [69]:
c1=np.reshape(c,(4,2))
print(c1)

[[ 44  55]
 [ 66  77]
 [ 88  99]
 [100 110]]


In [70]:
d.shape

(1, 4, 4)

In [76]:
d1=np.reshape(d,(1,8,2))
print(d1)

[[[12 24]
  [36 48]
  [77 70]
  [80 90]
  [45 68]
  [72 32]
  [74 12]
  [36 52]]]


In [77]:
d2=np.reshape(d,(1,2,2,2,2))
print(d2)

[[[[[12 24]
    [36 48]]

   [[77 70]
    [80 90]]]


  [[[45 68]
    [72 32]]

   [[74 12]
    [36 52]]]]]


In [81]:
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [85]:
#replace 2 with 34
b2=np.where(b==2,34,b)
print(b2)

[[ 1 34  3  4]
 [ 5  6  7  8]]


In [91]:
b[0,1]

np.int64(2)

In [89]:
#total of an array
sum(b) # sum is in column wise

array([ 6,  8, 10, 12])

In [ ]:
sum(sum(b)) #total sum

np.int64(36)

In [96]:
#min, max, total, mean, median, standard deviation
print("min",np.min(b))
print("max",np.max(b))
print("total",np.sum(b))
print("mean",np.mean(b))
print("median",np.median(b))
print("standard deviation",np.std(b))

min 1
max 8
total 36
mean 4.5
median 4.5
standard deviation 2.29128784747792


In [94]:
#square
np.square(b)

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

In [95]:
#sq_root
np.sqrt(b)

array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712]])

In [109]:
g=np.arange(10,20) #it create 1D array of given element range
print(g)

[10 11 12 13 14 15 16 17 18 19]


In [110]:
np.reshape(g,(5,2))

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])